import { useState } from 'react';
import {
  FileText,
  Search,
  Info,
  Filter,
  Grid,
  List,
  Download,
  Calendar,
} from 'lucide-react';
import { CornerPattern } from '../../components/layout';
import { InfoModal } from '../../components/features/common';
import type { InfoModalContent } from '../../components/features/common/InfoModal/InfoModal.types';

const infoContent: InfoModalContent = {
  whatFor:
    'Reports Library is your central archive for all historical and published reports.',
  whatItDoes: [
    'Browse all published reports.',
    'Search by date, type, or topic.',
    'Download reports for offline use.',
    'Share reports with external stakeholders.',
  ],
  whenToUse:
    'Use this screen to find historical reports or share published insights.',
  howToUse: [
    'Use the search bar to find specific reports.',
    'Filter by report type or date range.',
    'Click on a report to preview or download.',
  ],
  example: 'I search for last year Q4 report to compare with current data.',
  projectRelation:
    'The library provides a historical record of insights generated by the platform.',
};

const reports = [
  {
    title: 'UK Payment Trends 2025',
    category: 'Market',
    date: 'Jan 2025',
    downloads: 156,
  },
  {
    title: 'FCA Compliance Guide',
    category: 'Regulatory',
    date: 'Dec 2024',
    downloads: 89,
  },
  {
    title: 'Open Banking Impact Study',
    category: 'Research',
    date: 'Nov 2024',
    downloads: 234,
  },
  {
    title: 'Digital Wallet Adoption UK',
    category: 'Market',
    date: 'Oct 2024',
    downloads: 178,
  },
];

export default function ReportsLibrary() {
  const [showInfo, setShowInfo] = useState(false);
  const [viewMode, setViewMode] = useState<'grid' | 'list'>('grid');

  return (
    <div className="space-y-8 animate-in fade-in duration-500 relative">
      <CornerPattern />
      <InfoModal
        isOpen={showInfo}
        onClose={() => setShowInfo(false)}
        title="Reports Library"
        content={infoContent}
      />

      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 relative z-10">
        <div>
          <div className="flex items-center gap-3 mb-1">
            <h1 className="text-3xl font-bold tracking-tight text-foreground">
              Reports Library
            </h1>
            <button
              onClick={() => setShowInfo(true)}
              className="p-1.5 rounded-full bg-secondary text-muted-foreground hover:text-primary hover:bg-primary/10 transition-colors"
            >
              <Info className="w-5 h-5" />
            </button>
          </div>
          <p className="text-muted-foreground">
            Browse and download published reports.
          </p>
        </div>
      </div>

      <div className="flex flex-col sm:flex-row gap-4 items-center justify-between bg-card/80 backdrop-blur border border-border p-3 rounded-xl relative z-10">
        <div className="relative w-full sm:w-96 group">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
          <input
            type="text"
            placeholder="Search reports..."
            className="w-full pl-10 pr-4 py-2 bg-secondary/50 border border-transparent rounded-lg text-sm focus:bg-background focus:border-primary outline-none transition-all"
          />
        </div>
        <div className="flex items-center gap-2">
          <button className="p-2 hover:bg-secondary rounded-lg text-muted-foreground">
            <Filter className="w-4 h-4" />
          </button>
          <div className="h-6 w-px bg-border mx-1" />
          <button
            onClick={() => setViewMode('grid')}
            className={`p-2 rounded-lg ${viewMode === 'grid' ? 'bg-secondary text-foreground' : 'text-muted-foreground'}`}
          >
            <Grid className="w-4 h-4" />
          </button>
          <button
            onClick={() => setViewMode('list')}
            className={`p-2 rounded-lg ${viewMode === 'list' ? 'bg-secondary text-foreground' : 'text-muted-foreground'}`}
          >
            <List className="w-4 h-4" />
          </button>
        </div>
      </div>

      <div
        className={`relative z-10 ${viewMode === 'grid' ? 'grid md:grid-cols-2 lg:grid-cols-4 gap-4' : 'space-y-3'}`}
      >
        {reports.map((report, i) => (
          <div
            key={i}
            className={`card-base p-5 hover:border-primary/50 transition-all group cursor-pointer bg-card/80 backdrop-blur-sm ${viewMode === 'list' ? 'flex items-center gap-4' : ''}`}
          >
            <div
              className={`p-3 rounded-xl bg-secondary group-hover:bg-primary/10 transition-colors ${viewMode === 'list' ? '' : 'mb-4'}`}
            >
              <FileText className="w-5 h-5 text-primary" />
            </div>
            <div className="flex-1">
              <h3 className="font-bold text-sm group-hover:text-primary transition-colors">
                {report.title}
              </h3>
              <div className="flex items-center gap-2 text-xs text-muted-foreground mt-1">
                <span className="bg-secondary px-2 py-0.5 rounded">
                  {report.category}
                </span>
                <span>•</span>
                <span className="flex items-center gap-1">
                  <Calendar className="w-3 h-3" /> {report.date}
                </span>
              </div>
            </div>
            <div
              className={`flex items-center gap-2 ${viewMode === 'grid' ? 'mt-4 pt-4 border-t border-border' : ''}`}
            >
              <span className="text-xs text-muted-foreground">
                {report.downloads} downloads
              </span>
              <button className="ml-auto p-2 hover:bg-secondary rounded-lg text-muted-foreground hover:text-primary">
                <Download className="w-4 h-4" />
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
