import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';
import { InsightCard } from './InsightCard';

describe('InsightCard', () => {
  const defaultProps = {
    insight: 'Adoption of VRP is accelerating in the UK utility sector.',
    source: 'Insight Bot',
  };

  describe('rendering', () => {
    it('renders title', () => {
      render(<InsightCard {...defaultProps} />);
      expect(screen.getByText('Analyst Insight')).toBeInTheDocument();
    });

    it('renders insight text with quotes', () => {
      render(<InsightCard {...defaultProps} />);
      expect(
        screen.getByText(
          '"Adoption of VRP is accelerating in the UK utility sector."'
        )
      ).toBeInTheDocument();
    });

    it('renders source', () => {
      render(<InsightCard {...defaultProps} />);
      expect(screen.getByText(/Generated by Insight Bot/)).toBeInTheDocument();
    });

    it('renders timestamp when provided', () => {
      render(<InsightCard {...defaultProps} timestamp="Just now" />);
      expect(screen.getByText('Just now')).toBeInTheDocument();
    });

    it('does not render timestamp when not provided', () => {
      render(<InsightCard {...defaultProps} />);
      expect(screen.queryByText('Just now')).not.toBeInTheDocument();
    });

    it('applies testId when provided', () => {
      render(<InsightCard {...defaultProps} testId="test-insight" />);
      expect(screen.getByTestId('test-insight')).toBeInTheDocument();
    });

    it('applies custom className', () => {
      const { container } = render(
        <InsightCard {...defaultProps} className="custom-class" />
      );
      expect(container.firstChild).toHaveClass('custom-class');
    });
  });
});
