import React from 'react';
import { Sparkles } from 'lucide-react';
import { InsightCardProps } from './InsightCard.types';
import './InsightCard.css';

export const InsightCard: React.FC<InsightCardProps> = ({
  insight,
  source,
  timestamp,
  className = '',
  testId,
}) => {
  const classNames = ['insight-card', className].filter(Boolean).join(' ');

  return (
    <div className={classNames} data-testid={testId}>
      <div className="insight-card__header">
        <h3 className="insight-card__title">Analyst Insight</h3>
      </div>

      <blockquote className="insight-card__quote">"{insight}"</blockquote>

      <div className="insight-card__footer">
        <div className="insight-card__source">
          <span className="insight-card__source-icon">
            <Sparkles size={14} />
          </span>
          <span className="insight-card__source-text">
            Generated by {source}
          </span>
        </div>
        {timestamp && (
          <span className="insight-card__timestamp">{timestamp}</span>
        )}
      </div>

      <div className="insight-card__decoration" aria-hidden="true" />
    </div>
  );
};
